packages:
  - "apps/*"
  - "packages/*"
  - "scripts"

allowBuilds:
  esbuild: true
  msw: true

onlyBuiltDependencies:
  - esbuild
  - msw
catalog:
  "@types/node": ^24.12.4
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
  vitest: 4.1.10
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
