import { doRedirect } from "./utils/redirect.utils";

// Service worker registration with update handling (see issue #42).
//
// The service worker itself (generated by vite-plugin-pwa/Workbox) already
// activates new versions immediately via skipWaiting() + clientsClaim().
// However, the page that is currently open keeps running the old, already
// loaded assets: without extra handling, users only get the new version on
// the *next* navigation, which makes updates appear "one reload behind".
//
// To fix that, we register the service worker manually (injectRegister is
// disabled in vite.config.ts) and reload the page once a new worker takes
// control, so the freshly precached files are picked up right away.
if ("serviceWorker" in navigator) {
  // Whether a service worker was already controlling this page when it
  // loaded. On the very first visit there is no controller yet; in that case
  // the initial "controllerchange" only means the SW finished installing and
  // the page is already up to date, so reloading would be pointless.
  const hadController = navigator.serviceWorker.controller !== null;

  // Guards against reload loops: "controllerchange" can in theory fire more
  // than once, but we only ever want to trigger a single reload.
  let isReloading = false;

  // Fired when a new service worker takes control of this page, i.e. an
  // updated version of the app was installed and activated.
  navigator.serviceWorker.addEventListener("controllerchange", () => {
    if (!hadController || isReloading) {
      return;
    }

    isReloading = true;
    window.location.reload();
  });

  void navigator.serviceWorker.register("/sw.js");
}

(async () => {
  if (!(await doRedirect())) {
    // Only import modules when we actually need to render the UI
    const React = await import("react");
    await import("./index.css");
    await import("./utils/theme-init.utils");
    const { App } = await import("./app");
    const { createRoot } = await import("react-dom/client");

    const container = document.querySelector("#root");

    if (!container) {
      throw new Error("App container not found");
    }

    const root = createRoot(container);
    root.render(React.createElement(App));
  }
})();
