services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
  settings-sync:
    build: .
    restart: always
    environment:
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: 8080
      MONGO_URL: mongodb://root:pass@mongo:27017
      BASE_URL: http://localhost:8080
      JWT_SECRET: VHhEwqgRNZWwYZCl8aOfQ/VDVIl+yBuQtR+VbdUMxmA=
      GITHUB_CLIENT_ID: your_github_client_id
      GITHUB_CLIENT_SECRET: your_github_client_secret
    ports:
      - 8080:8080
    depends_on:
      - mongo
