name: Update Bang List

on:
  schedule:
    # Run on the 1st of every month at 2 AM UTC
    - cron: "0 2 1 * *"
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [main]
    paths: [".github/workflows/update-bangs.yml"] # Run when this workflow is updated

jobs:
  update-bangs:
    name: Update Bangs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0

      - name: Install dependencies
        run: bun install

      - name: Update bang list
        run: bun run update-bangs

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git switch --create update-bangs
          git add src/const/kagi-bangs.ts
          git commit -m "chore: update bang list from Kagi API"
          git push --force --set-upstream origin update-bangs

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "chore: update bang list from Kagi API" \
            --body "This PR updates the bang list from the Kagi API. Auto-generated by GitHub Actions." \
            --base main \
            --head update-bangs \
            --reviewer "${{ vars.UPDATE_BANGS_REVIEWERS }}" \
            || gh pr edit update-bangs \
            --title "chore: update bang list from Kagi API" \
            --body "This PR updates the bang list from the Kagi API. Auto-generated by GitHub Actions."
