name: Update Bang List

on:
  schedule:
    # Run on the 1st of every month at 2 AM UTC
    - cron: "0 2 1 * *"
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [main]
    paths: [".github/workflows/update-bangs.yml"] # Run when this workflow is updated

jobs:
  update-bangs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Update bang list
        run: node scripts/update-bangs.js

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/bang.ts
          git commit -m "chore: update bang list from Kagi API [skip ci]"
          git push

      - name: Build and deploy
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          npm run build
          echo "Bang list updated and built successfully!"
